"""Se adiciona tokens de pensamiento extendido

Revision ID: 48d2690d0070
Revises: 71188a7b2f9c
Create Date: 2025-04-11 10:16:05.523789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d2690d0070'
down_revision = '71188a7b2f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thinking_tokens', sa.Integer(), nullable=True))

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thinking_tokens', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_column('thinking_tokens')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('thinking_tokens')

    # ### end Alembic commands ###
