"""Primera migración - crear tabla usuario

Revision ID: 71188a7b2f9c
Revises: 
Create Date: 2025-04-10 14:06:49.875493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71188a7b2f9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('error_message')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
